### ISSUE TITLE
[SPRING] Android >4.4 must be supported!

### ISSUE THREAD

**Issue by pkcpkc** [SourcePointUSA/android-cmp-app#266]
Current SDK version does NOT support Android 4.4.

**Comment by atanurdemirci** [comment]
Hi Guys, 
this Issue is not really connected to the SDK. This is an issue with the Browser of Android 4.4. which is not fully compliant with ES6. Particular the Set() Function is causing the error. We have a branch ready which is supposed to fix this issue, it's currently in QA and supposed to be released once approved. We're going to add a polyfil to the Webview Content, so there is no need to update the SDK.

**Comment by pkcpkc** [comment]
Expected later this week.

**Comment by atanurdemirci** [comment]
@pkcpkc We have added a Polyfill for the Android Webviews which resolves this issue! This has been fixed in our Backend and should work without any action on your end.
